# Generated by Django 5.0.3 on 2024-04-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alumno_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='legajo',
        ),
        migrations.AddField(
            model_name='alumno',
            name='contraseña',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(default='default_value', max_length=30),
        ),
    ]
