# Generated by Django 5.0.3 on 2024-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='contraseña',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default='default_value', max_length=30),
        ),
    ]
